[package]
name = "avenir"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []

[dependencies.crossbeam-queue]
default-features = false
features = ["alloc"]
version = "0.3"

[dependencies.futures]
default-features = false
features = ["alloc"]
version = "0.3"

[dependencies.pin-project-lite]
default-features = false
version = "0.2"

[build-dependencies]
rustc_version = "0.4"
